- name: Install vault
  become: True
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 1800
    name:
      - vault

- name: Configure vault
  become: True
  template:
    src: vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    owner: root
    group: vault
    mode: 0640
  notify: restart vault
